"""Re-export all query functions for convenient imports."""
from bot.database.queries import (
    get_or_create_user,
    get_user,
    get_total_credits,
    consume_credit,
    refund_credit,
    add_credits,
    set_channel_subscribed,
    set_channel_unsubscribed,
    claim_subscription_bonus,
    mark_paywall_shown,
    mark_paywall_reminder_sent,
    get_pending_paywall_reminders,
    block_user,
    unblock_user,
    get_all_active_user_ids,
    get_admin_stats,
    get_sales_stats,
    get_styles,
    get_style,
    add_style,
    update_style_name,
    update_style_emoji,
    update_style_prompt,
    delete_style,
    ensure_default_styles,
    get_sessions,
    get_session,
    add_session,
    ensure_default_sessions,
    create_generation,
    complete_generation,
    fail_generation,
    create_payment,
    complete_payment,
    get_expired_unlocks,
    save_pending_unlock,
    get_pending_unlock,
    delete_pending_unlock,
    record_referral,
    get_referral_count,
)

__all__ = [
    "get_or_create_user", "get_user", "get_total_credits",
    "consume_credit", "refund_credit", "add_credits",
    "set_channel_subscribed", "set_channel_unsubscribed", "claim_subscription_bonus",
    "mark_paywall_shown",
    "mark_paywall_reminder_sent", "get_pending_paywall_reminders",
    "block_user", "unblock_user", "get_all_active_user_ids", "get_admin_stats", "get_sales_stats",
    "get_styles", "get_style", "add_style",
    "update_style_name", "update_style_emoji", "update_style_prompt", "delete_style",
    "ensure_default_styles",
    "get_sessions", "get_session", "add_session", "ensure_default_sessions",
    "create_generation", "complete_generation", "fail_generation",
    "create_payment", "complete_payment",
    "get_expired_unlocks", "save_pending_unlock", "get_pending_unlock", "delete_pending_unlock",
    "record_referral", "get_referral_count",
]
